# Generated by Django 3.1.1 on 2020-09-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200915_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.SlugField(),
        ),
    ]
